# Generated by Django 5.2.16 on 2026-07-17 19:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#3498DB', max_length=7)),
                ('icono', models.CharField(default='bi-wallet', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('BANCO', 'Institución Bancaria Tradicional'), ('BILLETERA', 'Billetera Digital / Prepago'), ('EFECTIVO', 'Gestión de Efectivo Manual'), ('COOPERATIVA', 'Cooperativa de Ahorro y Crédito')], default='BANCO', max_length=20)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('color_hex', models.CharField(default='#CCCCCC', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('simbolo', models.CharField(max_length=10)),
                ('decimales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=150, unique=True)),
                ('categoria_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios_administrados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(related_name='espacios_compartidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.espacio'),
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espacio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador_conector', models.CharField(blank=True, max_length=50, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='core.espacio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='core.institucionfinanciera')),
            ],
            options={
                'unique_together': {('espacio', 'institucion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_objetivo', models.IntegerField()),
                ('monto_actual', models.IntegerField(default=0)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercio_raw', models.CharField(max_length=255)),
                ('fecha_transaccion', models.DateTimeField()),
                ('monto_original', models.DecimalField(decimal_places=4, max_digits=15)),
                ('monto_clp', models.IntegerField()),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('tipo', models.CharField(choices=[('EGRESO', 'Gasto / Compra / Retiro'), ('INGRESO', 'Sueldo / Abono / Depósito'), ('TRANSFERENCIA', 'Transferencia entre Cuentas'), ('COMISION', 'Comisión / Interés Cobrado')], default='EGRESO', max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('conector_origen', models.CharField(default='gmail_bancoestado_v1', max_length=50)),
                ('gmail_message_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.categoria')),
                ('comercio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.comercio')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.cuentafinanciera')),
                ('moneda_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_originales', to='core.moneda')),
            ],
            options={
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('api_secret_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_texto', models.CharField(max_length=100)),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='core.espacio')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('espacio', 'nombre')},
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_limite', models.IntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='core.categoria')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='core.espacio')),
            ],
            options={
                'unique_together': {('espacio', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
