# Generated by Django 6.0.7 on 2026-07-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=128)),
                ('timestamp', models.PositiveIntegerField()),
                ('usado_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='core.perfilusuario')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='core_webhoo_timesta_797933_idx')],
                'unique_together': {('perfil', 'nonce')},
            },
        ),
    ]
