# Generated by Django 6.0.7 on 2026-07-18 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_webhook_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestaFallida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('conector', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_correo', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('motivo_error', models.CharField(max_length=255)),
                ('resuelto', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestas_fallidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
