# Generated by Django 6.0.7 on 2026-07-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingesta_fallida'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='secret_revelado',
            field=models.BooleanField(default=False, help_text='True cuando el usuario confirmó haber guardado el secreto (ya no se muestra en claro).'),
        ),
    ]
