# Generated by Django 6.0.7 on 2026-07-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_secret_revelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_raw', models.CharField(max_length=150, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.comercio')),
            ],
            options={
                'verbose_name_plural': 'Aliases de comercio',
            },
        ),
    ]
